export interface GameState {
  geld: number;
  nahrung: number;
  sauerstoff: number;
  mineralien: number;
  gesundheit: number;
  wissen: number;
  zufriedenheit: number;
  angst: number;
  planetZustand: number;
  tag: number;
  fct: number;
  population: number;
  workers: number;
  engineers: number;
  children: number;
  drones: number;
  dronesCapacity?: number;
  efficiency: number;
  netIncome: number;
  netIncomeDetails?: { food: number; o2: number; foodProduced: number; o2Produced: number; mineralsProduced: number; consumed: number; };
  steuerStufe: number;
  taxLevel?: number;
  cooldowns?: Record<string, number>;
  factions: { [key: string]: { loyalty: number } };
  workersLocked?: number;
  constructionEngineersLocked?: number;
  dronesEngineersLocked?: number;
  popWorkers?: number;
  popEngineers?: number;
  popChildren?: number;
  schoolEnrollments?: { qty: number }[];
  academyEnrollments?: { qty: number }[];
  techs?: Record<string, boolean>;
}
